### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#19]
Header is not correctly done.
![image](https://user-images.githubusercontent.com/128583729/236160866-89bb1424-61cf-4593-be2d-2acd6c78c6d3.png)

**Comment by amritab3** [comment]
![image](https://github.com/PunMahesh/aims/assets/104433446/4008a2ae-72dc-49bb-9981-3697e63638a3)
Header fixed.

**Comment by KanchanAMS** [comment]
#Issue solved
