### ISSUE TITLE
Page alignment not met according to the design

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#2]
![Screenshot 2023-03-29 155247](https://user-images.githubusercontent.com/128583729/228502984-b2d4d885-0483-470c-8f4c-0fce3639c07e.png)

**Comment by amritab3** [comment]
Page alignment fixed. 
![image](https://user-images.githubusercontent.com/104433446/229296510-ed4ee615-b17f-43e5-a357-66684c1f6e73.png)
