### ISSUE TITLE
Registration 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#22]
Registration page isn't done as per the Design.
![image](https://user-images.githubusercontent.com/128583729/236164670-ef3481ff-bfdf-496e-bdad-c860e9bca671.png)

**Comment by amritab3** [comment]
![image](https://github.com/PunMahesh/aims/assets/104433446/339235ff-058f-495c-b1ea-872cbe396c65)
Registration Fixed.
