### ISSUE TITLE
Arrow Issue

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#3]
![Screenshot 2023-03-29 160541](https://user-images.githubusercontent.com/128583729/228504759-3ba99c0e-5453-443b-af67-446dd8ccd590.png)

**Comment by amritab3** [comment]
Arrow issue fixed. 
![image](https://user-images.githubusercontent.com/104433446/229296598-3f2eef52-d3db-478d-b5e4-105e23bef24e.png)

**Comment by sapkotarajat** [comment]
It seems the background of that particular element is not dissolving to existing background.

**Comment by sapkotarajat** [comment]
![image](https://user-images.githubusercontent.com/95966103/230709285-496479ac-92ea-49ea-92f1-fb55889cdb6b.png)

Updated
