### ISSUE TITLE
Capitalize the Case

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#36]
![case](https://github.com/PunMahesh/aims/assets/128583729/41618a91-cbd3-4b77-8cfb-15d3ceedbacc)

**Comment by PunMahesh** [comment]
![Make capital field](https://github.com/PunMahesh/aims/assets/126581836/ee6f1412-7663-4cff-8b68-f68e3989e2f3)

**Comment by PunMahesh** [comment]
All required case are capitalized.
