### ISSUE TITLE
I cannot login my superuser with custom password i have set certain password on m y own which is in database

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#39]
![I_can_not_login_my_superuser_with_custom_password_I_have_set_certain_password_on_my_own_which_is_in_database_and_while_login_in_it_it_tries_to_validate_my_password_instead_checking_what_is_in_database](https://github.com/PunMahesh/aims/assets/128583729/9bdff704-82db-4508-8298-e8e9f54cdb60)

**Comment by amritab3** [comment]
Seems like your local code is not updated with origin main. Please pull the latest changes and try it again.  In case the error still remains , please try the following:
  
You created that user before we had password validation. Now you need to create a new account with password that meets all the requirements. 

- password must be 8 characters or more 
- password must contain at least 1 uppercase letter
- password must contain at least 1 number

**Comment by PunMahesh** [comment]
![image](https://github.com/PunMahesh/aims/assets/126581836/cff3f590-c34c-4995-b2ca-779825a251d7)

**Comment by PunMahesh** [comment]
fixed now user can login with custom password.

**Comment by PunMahesh** [comment]
![image](https://github.com/PunMahesh/aims/assets/126581836/2fba31a8-5096-430b-bdbf-230e86e0da34)

**Comment by PunMahesh** [comment]
![Screenshot 2023-05-13 191903](https://github.com/PunMahesh/aims/assets/126581836/da76888c-1718-4348-9cb2-520299482483)

**Comment by PunMahesh** [comment]
The given issue is fixed as user can use custom password to login as admin as well.
