### ISSUE TITLE
use anchor tags for the useful links in the footer 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#4]
![Screenshot 2023-03-29 161243](https://user-images.githubusercontent.com/128583729/228506195-e5211d80-6c3b-402d-a48e-9bdc183b0f7c.png)

**Comment by amritab3** [comment]
Using anchor tag in footer . 
![image](https://user-images.githubusercontent.com/104433446/229296850-65cc1333-d969-4e05-b20f-6569fabd4515.png)

![image](https://user-images.githubusercontent.com/104433446/229296722-b73c3c50-f359-415f-8dad-26d77b4723c8.png)
