### ISSUE TITLE
make Fields Required So That No Empty Dataset Would Be Saved

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#41]
![makeFieldsRequiredSoThatNoEmptyDatasetWouldBeSaved](https://github.com/PunMahesh/aims/assets/128583729/ac56d74b-74dd-4d5a-9de7-41988c814727)

**Comment by PunMahesh** [comment]
![Make field required for adding](https://github.com/PunMahesh/aims/assets/126581836/26edcfd6-4265-47e0-bd2c-5aa4e64d85f2)

**Comment by PunMahesh** [comment]
Empty field can not be added.
