### ISSUE TITLE
Pasport Field adoptation

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#42]
![passportfieldoptional](https://github.com/PunMahesh/aims/assets/128583729/3b6e4c76-45ff-4e24-9a05-10beec1c5018)

**Comment by PunMahesh** [comment]
![passport field can be added](https://github.com/PunMahesh/aims/assets/126581836/b8d7eb85-646a-4aed-90c9-dc999e35f6d1)

**Comment by PunMahesh** [comment]
Passport can be added properly now.
