### ISSUE TITLE
Fix the Container 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#43]
![image](https://github.com/PunMahesh/aims/assets/128583729/5b4ae944-345e-4ebb-9fcd-79960cdd1f1c)

**Comment by amritab3** [comment]
@PunMahesh  please the css as you adding the validation messed it up. I had fixed KYC page the day before yesterday. 

![image](https://github.com/PunMahesh/aims/assets/104433446/6456e4ba-ebde-4e8e-a618-68e38a373034)
![image](https://github.com/PunMahesh/aims/assets/104433446/1aa4ba65-ac6f-4528-bdda-d6cd80b37cd0)
![image](https://github.com/PunMahesh/aims/assets/104433446/17784df4-92f9-4fb8-9d82-ae1bd60c6487)
![image](https://github.com/PunMahesh/aims/assets/104433446/4c1f0b1c-3720-46f7-9b49-00893e8ed7fc)
![image](https://github.com/PunMahesh/aims/assets/104433446/dbbfd9b4-3f78-46f3-8364-9e5681b6f0e3)
![image](https://github.com/PunMahesh/aims/assets/104433446/8dada5ae-a1e2-4809-883a-e49944394fb0)

@KanchanAMS please assign this issue to @PunMahesh
