### ISSUE TITLE
Article Title not showing 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#44]
![Article titlr](https://github.com/PunMahesh/aims/assets/128583729/f6c3830d-31d2-470e-8d9f-58aabacdc234)

**Comment by PunMahesh** [comment]
![Article TITLE ISSUR REAL](https://github.com/PunMahesh/aims/assets/126581836/7bc1b1db-f8c4-4a38-b5a8-4cb84d9b6b50)

**Comment by PunMahesh** [comment]
Title appears perfectly.
