### ISSUE TITLE
Hover should be in color yellow while hovering and green static

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#45]
![Header ](https://github.com/PunMahesh/aims/assets/128583729/2a3d4d3d-484d-4def-b9e5-4a4af0c187ad)

**Comment by amritab3** [comment]
[PR link](https://github.com/PunMahesh/aims/pull/50)

![image](https://github.com/PunMahesh/aims/assets/104433446/3e35cec0-21b4-4bb3-9f9e-a5b020ff807d)
![image](https://github.com/PunMahesh/aims/assets/104433446/2386fd3d-8003-40bc-87ff-e04860f24745)
![image](https://github.com/PunMahesh/aims/assets/104433446/8ec87395-190e-4b9f-a1c8-f8860127e765)
