### ISSUE TITLE
Spacing should be equal is both side of the home page

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#46]
![spacing](https://github.com/PunMahesh/aims/assets/128583729/5a4d0b01-5130-4ca5-ac23-899e30cc0f8c)

**Comment by amritab3** [comment]
![image](https://github.com/PunMahesh/aims/assets/104433446/5f2a803d-f558-417d-a664-ca12b11ee669)

Issue Solved.

**Comment by amritab3** [comment]
![image](https://github.com/PunMahesh/aims/assets/104433446/27d25fe8-e7dd-498d-becc-2fb15903a61f)

Issue Solved.
