### ISSUE TITLE
Please make Organic fruit and organic vegetable cotaneer close to the image or make the container little big according to the design

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#48]
![image](https://github.com/PunMahesh/aims/assets/128583729/6d62977d-dbaf-49c2-b0b6-51ce2fd64e35)

**Comment by amritab3** [comment]
![image](https://github.com/PunMahesh/aims/assets/104433446/b30150a1-d6e1-4337-8d89-f44d55bbd88f)

Issue solved.
