### ISSUE TITLE
spacing in the middle is too much 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#49]
![image](https://github.com/PunMahesh/aims/assets/128583729/ffca8fbe-2afd-41b0-9fa7-7a8d63aa8b9c)

**Comment by amritab3** [comment]
![image](https://github.com/PunMahesh/aims/assets/104433446/17c48704-7e60-4e34-9c8f-b1bd2312be41)

space reduced.

**Comment by KanchanAMS** [comment]
# issue solved
