### ISSUE TITLE
User not authenticated

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#5]
![image](https://user-images.githubusercontent.com/128583729/228907240-39c6e07c-4dcb-449c-88a9-9dcb741439f5.png)

**Comment by PunMahesh** [comment]
![Screenshot 2023-04-01 232117](https://user-images.githubusercontent.com/126581836/229306048-2c382c32-23bf-412d-9dd6-39cc4fdcac4e.png)

**Comment by PunMahesh** [comment]
The given issue is fixed.
