### ISSUE TITLE
Email not sent when forgot password is pressed 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#6]
![image](https://user-images.githubusercontent.com/128583729/228907914-37d6a1f1-a01e-4866-a9c3-54f561115eb8.png)

**Comment by PunMahesh** [comment]
![Screenshot 2023-04-01 222805](https://user-images.githubusercontent.com/126581836/229303789-73ddf2cc-360a-49df-b296-6c00f670ddd4.png)

**Comment by PunMahesh** [comment]
![Screenshot 2023-04-01 222833](https://user-images.githubusercontent.com/126581836/229303836-40cde765-48f9-42b9-9823-bb78d05c025c.png)

**Comment by PunMahesh** [comment]
![Screenshot 2023-04-01 222858](https://user-images.githubusercontent.com/126581836/229303860-bfd92ddd-f8fa-4d63-a06e-34f14e6a7b84.png)

**Comment by PunMahesh** [comment]
The given issue is solved @KanchanAMS
