### ISSUE TITLE
Assign margin on the side of the page 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#7]
![image](https://user-images.githubusercontent.com/128583729/228916791-02956782-ed35-48d5-8c14-f921a38b56cf.png)

**Comment by parasksee** [comment]
fixed
![addcrop](https://user-images.githubusercontent.com/37445779/229276935-80666adc-bef3-45af-8c97-60acb7bf1d77.png)

**Comment by parasksee** [comment]
fixed
![addcrop updated](https://user-images.githubusercontent.com/37445779/229277167-726e0117-64d4-4a81-88e0-d3ca5736f2bd.png)
