### ISSUE TITLE
Login page is not as per the design 

### ISSUE THREAD

**Issue by KanchanAMS** [PunMahesh/aims#8]
![image](https://user-images.githubusercontent.com/128583729/228920870-822dc4c4-fe95-441f-ba0e-08d337095add.png)

**Comment by parasksee** [comment]
Fixed
![Screenshot 2023-03-31 230501](https://user-images.githubusercontent.com/37445779/229187886-0473eafa-542b-44f4-a9f3-d455ac32533e.png)
